<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<div class="block">
<div class="block-title">
<strong><?php echo $this->__('BestSeller') ?></strong>
</div>
<?php $_collectionSize = count($_products->getItems()) ?>
<ul class="bestsellerdatawrapper">
<?php $i=1; foreach ($_products->getItems() as $_product): ?>
    <?php if ($i%1!==0): ?>
    
    <?php endif ?>
        <li>
            
            <div class="bestsellerimg">
            <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(100, 100); ?>" width="100" height="100" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
            </a>
            </div>
            <div class="bestsellerdata">
            <h3 class="product-name"><?php echo $this->htmlEscape($_product->getName()) ?></h3>            
                <?php echo $this->getPriceHtml($_product, true) ?>            
            </div>
    </li>
    <?php if ($i%3==0 or $i==$_collectionSize): ?>
  
    <?php endif ?>
  <?php $i++; endforeach; $kol = $_collectionSize; ?>
</ul>
<?php endif; ?>
</div>