<?php
    $_productCollection=$_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output'); 
	$_collectionSize = $_productCollection->count();
?>

<div class="latest-products-info">
  <h1><span><?php echo $this->__('Featured Products') ?></span></h1>
  <?php if($_collectionSize>0)
{
	?>
  <div id="owl-demo3" class="owl-carousel owl-theme">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
    <?php if($i==10) break; ?>
    <?php if ($i++%$_columnCount==0): ?>
    <?php endif ?>
    <?php /*if ($i++%$_columnCount==0): ?>
            <?php endif*/ ?>
    <div class="item">
      <div class="products-img"> <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
        <?php /* Based on the native RWD styling, product images are displayed at a max of ~400px wide when viewed on a
                        one column page layout with four product columns from a 1280px viewport. For bandwidth reasons,
                        we are going to serve a 300px image, as it will look fine at 400px and most of the times, the image
                        will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
                        This $_imgSize value could even be decreased further, based on the page layout
                        (one column, two column, three column) and number of product columns. */ ?>
        <?php $_imgSize = 300; ?>
        <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> </a> </div>
      <div class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
        <?php $prod_name = $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
        <?php
                    $count_str = strlen($prod_name);
                    if ($count_str < 50) {
                        echo $prod_name;
                    } else {
                        $offset = 0;
                        $length = 51;   
                        $prod_name = html_entity_decode($prod_name);                     
                        echo htmlentities(mb_substr($prod_name,0,$length,'utf-8')). "...";;                        
                    }
                    ?>
        </a></div>    
      <?php //if($_product->getRatingSummary()): ?>
      <?php //echo $this->getReviewsSummaryHtml($_product, 'short') ?>
      <?php //endif; ?>
      <div class="div-add">
        <div class="addtocart">
        <!-- NOT2ORDER EDITED -->
                            <?php if (Mage::getConfig()->getModuleConfig('Ophirah_Qquoteadv')->is('active', 'true') && (int)Mage::getStoreConfig('qquoteadv_quote_frontend/catalog/layout_update_listgrid_activated', Mage::app()->getStore()->getStoreId()) == 1): ?>
                                <?php if (Mage::helper('qquoteadv/not2order')->getShowPrice($_product)) : ?>
                                    <?php echo $this->getPriceHtml($_product, true) ?>
                                <?php endif; ?>
                            <?php elseif (Mage::getConfig()->getModuleConfig('Ophirah_Not2Order')->is('active', 'true')): ?>
                                <?php if (Mage::helper('not2order')->getShowPrice($_product)) : ?>
                                    <?php echo $this->getPriceHtml($_product, true); ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <!-- END NOT2ORDER EDITED -->
          <!-- NOT2ORDER EDITED -->
                                <?php if (!$_product->canConfigure()): ?>
                                    <?php if (Mage::getConfig()->getModuleConfig('Ophirah_Qquoteadv')->is('active', 'true') && Mage::helper('qquoteadv')->isEnabled() && (int)Mage::getStoreConfig('qquoteadv_quote_frontend/catalog/layout_update_listgrid_activated', Mage::app()->getStore()->getStoreId()) == 1): ?>
                                        <?php echo Mage::app()->getLayout()->createBlock('qquoteadv/qquotebtn')->setData('product', $_product)->setTemplate('qquoteadv/catalog/product/c2qBtnGrid.phtml')->toHtml(); ?>
                                    <?php elseif (Mage::getConfig()->getModuleConfig('Ophirah_Not2Order')->is('active', 'true')): ?>
                                        <?php if ($_product->isSaleable()): ?>
                                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                                <span><span><?php echo $this->__('Add to Cart') ?></span></span>
                                            </button>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php if (Mage::getConfig()->getModuleConfig('Ophirah_Not2Order')->is('active', 'true')): ?>
                                    <?php if ($_product->isAvailable() && $_product->canConfigure()): ?>
                                        <!-- END NOT2ORDER EDITED -->
                                        <a title="<?php echo $this->__('View Details') ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                                    <?php endif; ?>

                                    <?php if (!$_product->isAvailable()) : ?>
                                        <p class="availability out-of-stock">
                                            <span><?php echo $this->__('Out of stock') ?></span>
                                        </p>
                                    <?php endif; ?>
                                <?php endif; ?>
        </div>
        <div class="add-to-wishlist">
          <?php if ($this->helper('wishlist')->isAllow()) : ?>
          <a data-toggle="tooltip" data-placement="top" data-html="true" title="<?php echo $this->__('Add to Wishlist') ?>" class="wishlist" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Add to Wishlist') ?></a>
          <?php endif; ?>
        </div>
        <div class="add-to-compare">
          <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
          <a data-toggle="tooltip" data-placement="top" data-html="true" title="<?php echo $this->__('Add to Compare') ?>" class="compare" href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a>
          <?php endif; ?>
        </div>
      </div>
    </div>
    <?php /*if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            <?php endif*/ ?>
    <?php endforeach ?>
  </div>
  <?php } ?>
  <?php if(!$_productCollection->count()){ ?>
  <div class="note-msg"> <?php echo $this->__('There are no products matching the selection.') ?> </div>
  <?php } ?>
</div>
